package com.lab.sdt.dao;

import com.lab.sdt.model.Material;
import com.lab.sdt.model.MaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	long countByExample(MaterialExample example);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int deleteByExample(MaterialExample example);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int deleteByPrimaryKey(Integer idmaterial);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int insert(Material record);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int insertSelective(Material record);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	List<Material> selectByExample(MaterialExample example);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	Material selectByPrimaryKey(Integer idmaterial);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Material record, @Param("example") MaterialExample example);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByExample(@Param("record") Material record, @Param("example") MaterialExample example);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByPrimaryKeySelective(Material record);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByPrimaryKey(Material record);



	List<Material> selectByMaterial(String material);
    
   
    
    Material selectByNoSerie(String n_serie);
}