package com.lab.sdt.dao;

import com.lab.sdt.model.Ubicacion;
import com.lab.sdt.model.UbicacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UbicacionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	long countByExample(UbicacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int deleteByExample(UbicacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int deleteByPrimaryKey(Integer idestimulacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int insert(Ubicacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int insertSelective(Ubicacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	List<Ubicacion> selectByExample(UbicacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	Ubicacion selectByPrimaryKey(Integer idestimulacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Ubicacion record, @Param("example") UbicacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByExample(@Param("record") Ubicacion record, @Param("example") UbicacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByPrimaryKeySelective(Ubicacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ubicacion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	int updateByPrimaryKey(Ubicacion record);
}