package com.lab.sdt.model;

import java.util.Date;

public class Electroretinografia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.idElectro
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer idelectro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.idExpConsulta
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer idexpconsulta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.AIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer aizq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.ADer
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer ader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.BIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer bizq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.BDder
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Integer bdder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electroretinografia.fechaE
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    private Date fechae;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.idElectro
     *
     * @return the value of electroretinografia.idElectro
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getIdelectro() {
        return idelectro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.idElectro
     *
     * @param idelectro the value for electroretinografia.idElectro
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setIdelectro(Integer idelectro) {
        this.idelectro = idelectro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.idExpConsulta
     *
     * @return the value of electroretinografia.idExpConsulta
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getIdexpconsulta() {
        return idexpconsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.idExpConsulta
     *
     * @param idexpconsulta the value for electroretinografia.idExpConsulta
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setIdexpconsulta(Integer idexpconsulta) {
        this.idexpconsulta = idexpconsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.AIzq
     *
     * @return the value of electroretinografia.AIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getAizq() {
        return aizq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.AIzq
     *
     * @param aizq the value for electroretinografia.AIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setAizq(Integer aizq) {
        this.aizq = aizq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.ADer
     *
     * @return the value of electroretinografia.ADer
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getAder() {
        return ader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.ADer
     *
     * @param ader the value for electroretinografia.ADer
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setAder(Integer ader) {
        this.ader = ader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.BIzq
     *
     * @return the value of electroretinografia.BIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getBizq() {
        return bizq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.BIzq
     *
     * @param bizq the value for electroretinografia.BIzq
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setBizq(Integer bizq) {
        this.bizq = bizq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.BDder
     *
     * @return the value of electroretinografia.BDder
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Integer getBdder() {
        return bdder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.BDder
     *
     * @param bdder the value for electroretinografia.BDder
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setBdder(Integer bdder) {
        this.bdder = bdder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electroretinografia.fechaE
     *
     * @return the value of electroretinografia.fechaE
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public Date getFechae() {
        return fechae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electroretinografia.fechaE
     *
     * @param fechae the value for electroretinografia.fechaE
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    public void setFechae(Date fechae) {
        this.fechae = fechae;
    }
}