package com.lab.sdt.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExpedienteConsultaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public ExpedienteConsultaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdexpeconsulIsNull() {
            addCriterion("idExpeConsul is null");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulIsNotNull() {
            addCriterion("idExpeConsul is not null");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulEqualTo(Integer value) {
            addCriterion("idExpeConsul =", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulNotEqualTo(Integer value) {
            addCriterion("idExpeConsul <>", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulGreaterThan(Integer value) {
            addCriterion("idExpeConsul >", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulGreaterThanOrEqualTo(Integer value) {
            addCriterion("idExpeConsul >=", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulLessThan(Integer value) {
            addCriterion("idExpeConsul <", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulLessThanOrEqualTo(Integer value) {
            addCriterion("idExpeConsul <=", value, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulIn(List<Integer> values) {
            addCriterion("idExpeConsul in", values, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulNotIn(List<Integer> values) {
            addCriterion("idExpeConsul not in", values, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulBetween(Integer value1, Integer value2) {
            addCriterion("idExpeConsul between", value1, value2, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andIdexpeconsulNotBetween(Integer value1, Integer value2) {
            addCriterion("idExpeConsul not between", value1, value2, "idexpeconsul");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaIsNull() {
            addCriterion("fechaConsulta is null");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaIsNotNull() {
            addCriterion("fechaConsulta is not null");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaEqualTo(Date value) {
            addCriterionForJDBCDate("fechaConsulta =", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaNotEqualTo(Date value) {
            addCriterionForJDBCDate("fechaConsulta <>", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaGreaterThan(Date value) {
            addCriterionForJDBCDate("fechaConsulta >", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fechaConsulta >=", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaLessThan(Date value) {
            addCriterionForJDBCDate("fechaConsulta <", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fechaConsulta <=", value, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaIn(List<Date> values) {
            addCriterionForJDBCDate("fechaConsulta in", values, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaNotIn(List<Date> values) {
            addCriterionForJDBCDate("fechaConsulta not in", values, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fechaConsulta between", value1, value2, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andFechaconsultaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fechaConsulta not between", value1, value2, "fechaconsulta");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteIsNull() {
            addCriterion("idExpediente is null");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteIsNotNull() {
            addCriterion("idExpediente is not null");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteEqualTo(Integer value) {
            addCriterion("idExpediente =", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteNotEqualTo(Integer value) {
            addCriterion("idExpediente <>", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteGreaterThan(Integer value) {
            addCriterion("idExpediente >", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("idExpediente >=", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteLessThan(Integer value) {
            addCriterion("idExpediente <", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteLessThanOrEqualTo(Integer value) {
            addCriterion("idExpediente <=", value, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteIn(List<Integer> values) {
            addCriterion("idExpediente in", values, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteNotIn(List<Integer> values) {
            addCriterion("idExpediente not in", values, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteBetween(Integer value1, Integer value2) {
            addCriterion("idExpediente between", value1, value2, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andIdexpedienteNotBetween(Integer value1, Integer value2) {
            addCriterion("idExpediente not between", value1, value2, "idexpediente");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andPesoIsNull() {
            addCriterion("peso is null");
            return (Criteria) this;
        }

        public Criteria andPesoIsNotNull() {
            addCriterion("peso is not null");
            return (Criteria) this;
        }

        public Criteria andPesoEqualTo(String value) {
            addCriterion("peso =", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoNotEqualTo(String value) {
            addCriterion("peso <>", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoGreaterThan(String value) {
            addCriterion("peso >", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoGreaterThanOrEqualTo(String value) {
            addCriterion("peso >=", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoLessThan(String value) {
            addCriterion("peso <", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoLessThanOrEqualTo(String value) {
            addCriterion("peso <=", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoLike(String value) {
            addCriterion("peso like", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoNotLike(String value) {
            addCriterion("peso not like", value, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoIn(List<String> values) {
            addCriterion("peso in", values, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoNotIn(List<String> values) {
            addCriterion("peso not in", values, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoBetween(String value1, String value2) {
            addCriterion("peso between", value1, value2, "peso");
            return (Criteria) this;
        }

        public Criteria andPesoNotBetween(String value1, String value2) {
            addCriterion("peso not between", value1, value2, "peso");
            return (Criteria) this;
        }

        public Criteria andPMayorIsNull() {
            addCriterion("p_mayor is null");
            return (Criteria) this;
        }

        public Criteria andPMayorIsNotNull() {
            addCriterion("p_mayor is not null");
            return (Criteria) this;
        }

        public Criteria andPMayorEqualTo(String value) {
            addCriterion("p_mayor =", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorNotEqualTo(String value) {
            addCriterion("p_mayor <>", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorGreaterThan(String value) {
            addCriterion("p_mayor >", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorGreaterThanOrEqualTo(String value) {
            addCriterion("p_mayor >=", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorLessThan(String value) {
            addCriterion("p_mayor <", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorLessThanOrEqualTo(String value) {
            addCriterion("p_mayor <=", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorLike(String value) {
            addCriterion("p_mayor like", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorNotLike(String value) {
            addCriterion("p_mayor not like", value, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorIn(List<String> values) {
            addCriterion("p_mayor in", values, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorNotIn(List<String> values) {
            addCriterion("p_mayor not in", values, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorBetween(String value1, String value2) {
            addCriterion("p_mayor between", value1, value2, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMayorNotBetween(String value1, String value2) {
            addCriterion("p_mayor not between", value1, value2, "pMayor");
            return (Criteria) this;
        }

        public Criteria andPMenorIsNull() {
            addCriterion("p_menor is null");
            return (Criteria) this;
        }

        public Criteria andPMenorIsNotNull() {
            addCriterion("p_menor is not null");
            return (Criteria) this;
        }

        public Criteria andPMenorEqualTo(String value) {
            addCriterion("p_menor =", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorNotEqualTo(String value) {
            addCriterion("p_menor <>", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorGreaterThan(String value) {
            addCriterion("p_menor >", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorGreaterThanOrEqualTo(String value) {
            addCriterion("p_menor >=", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorLessThan(String value) {
            addCriterion("p_menor <", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorLessThanOrEqualTo(String value) {
            addCriterion("p_menor <=", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorLike(String value) {
            addCriterion("p_menor like", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorNotLike(String value) {
            addCriterion("p_menor not like", value, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorIn(List<String> values) {
            addCriterion("p_menor in", values, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorNotIn(List<String> values) {
            addCriterion("p_menor not in", values, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorBetween(String value1, String value2) {
            addCriterion("p_menor between", value1, value2, "pMenor");
            return (Criteria) this;
        }

        public Criteria andPMenorNotBetween(String value1, String value2) {
            addCriterion("p_menor not between", value1, value2, "pMenor");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIsNull() {
            addCriterion("temperatura is null");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIsNotNull() {
            addCriterion("temperatura is not null");
            return (Criteria) this;
        }

        public Criteria andTemperaturaEqualTo(String value) {
            addCriterion("temperatura =", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotEqualTo(String value) {
            addCriterion("temperatura <>", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaGreaterThan(String value) {
            addCriterion("temperatura >", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaGreaterThanOrEqualTo(String value) {
            addCriterion("temperatura >=", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaLessThan(String value) {
            addCriterion("temperatura <", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaLessThanOrEqualTo(String value) {
            addCriterion("temperatura <=", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaLike(String value) {
            addCriterion("temperatura like", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotLike(String value) {
            addCriterion("temperatura not like", value, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaIn(List<String> values) {
            addCriterion("temperatura in", values, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotIn(List<String> values) {
            addCriterion("temperatura not in", values, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaBetween(String value1, String value2) {
            addCriterion("temperatura between", value1, value2, "temperatura");
            return (Criteria) this;
        }

        public Criteria andTemperaturaNotBetween(String value1, String value2) {
            addCriterion("temperatura not between", value1, value2, "temperatura");
            return (Criteria) this;
        }

        public Criteria andAlturaIsNull() {
            addCriterion("altura is null");
            return (Criteria) this;
        }

        public Criteria andAlturaIsNotNull() {
            addCriterion("altura is not null");
            return (Criteria) this;
        }

        public Criteria andAlturaEqualTo(String value) {
            addCriterion("altura =", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaNotEqualTo(String value) {
            addCriterion("altura <>", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaGreaterThan(String value) {
            addCriterion("altura >", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaGreaterThanOrEqualTo(String value) {
            addCriterion("altura >=", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaLessThan(String value) {
            addCriterion("altura <", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaLessThanOrEqualTo(String value) {
            addCriterion("altura <=", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaLike(String value) {
            addCriterion("altura like", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaNotLike(String value) {
            addCriterion("altura not like", value, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaIn(List<String> values) {
            addCriterion("altura in", values, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaNotIn(List<String> values) {
            addCriterion("altura not in", values, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaBetween(String value1, String value2) {
            addCriterion("altura between", value1, value2, "altura");
            return (Criteria) this;
        }

        public Criteria andAlturaNotBetween(String value1, String value2) {
            addCriterion("altura not between", value1, value2, "altura");
            return (Criteria) this;
        }

        public Criteria andMasaCorpIsNull() {
            addCriterion("masa_corp is null");
            return (Criteria) this;
        }

        public Criteria andMasaCorpIsNotNull() {
            addCriterion("masa_corp is not null");
            return (Criteria) this;
        }

        public Criteria andMasaCorpEqualTo(String value) {
            addCriterion("masa_corp =", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpNotEqualTo(String value) {
            addCriterion("masa_corp <>", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpGreaterThan(String value) {
            addCriterion("masa_corp >", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpGreaterThanOrEqualTo(String value) {
            addCriterion("masa_corp >=", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpLessThan(String value) {
            addCriterion("masa_corp <", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpLessThanOrEqualTo(String value) {
            addCriterion("masa_corp <=", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpLike(String value) {
            addCriterion("masa_corp like", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpNotLike(String value) {
            addCriterion("masa_corp not like", value, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpIn(List<String> values) {
            addCriterion("masa_corp in", values, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpNotIn(List<String> values) {
            addCriterion("masa_corp not in", values, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpBetween(String value1, String value2) {
            addCriterion("masa_corp between", value1, value2, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andMasaCorpNotBetween(String value1, String value2) {
            addCriterion("masa_corp not between", value1, value2, "masaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpIsNull() {
            addCriterion("grasa_corp is null");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpIsNotNull() {
            addCriterion("grasa_corp is not null");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpEqualTo(String value) {
            addCriterion("grasa_corp =", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpNotEqualTo(String value) {
            addCriterion("grasa_corp <>", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpGreaterThan(String value) {
            addCriterion("grasa_corp >", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpGreaterThanOrEqualTo(String value) {
            addCriterion("grasa_corp >=", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpLessThan(String value) {
            addCriterion("grasa_corp <", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpLessThanOrEqualTo(String value) {
            addCriterion("grasa_corp <=", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpLike(String value) {
            addCriterion("grasa_corp like", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpNotLike(String value) {
            addCriterion("grasa_corp not like", value, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpIn(List<String> values) {
            addCriterion("grasa_corp in", values, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpNotIn(List<String> values) {
            addCriterion("grasa_corp not in", values, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpBetween(String value1, String value2) {
            addCriterion("grasa_corp between", value1, value2, "grasaCorp");
            return (Criteria) this;
        }

        public Criteria andGrasaCorpNotBetween(String value1, String value2) {
            addCriterion("grasa_corp not between", value1, value2, "grasaCorp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expediente_consulta
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:29:25 CDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table expediente_consulta
     *
     * @mbg.generated Thu Sep 05 18:29:25 CDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}