package com.lab.sdt.dao;

import com.lab.sdt.model.Electroretinografia;
import com.lab.sdt.model.ElectroretinografiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElectroretinografiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    long countByExample(ElectroretinografiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int deleteByExample(ElectroretinografiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int deleteByPrimaryKey(Integer idelectro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int insert(Electroretinografia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int insertSelective(Electroretinografia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    List<Electroretinografia> selectByExample(ElectroretinografiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    Electroretinografia selectByPrimaryKey(Integer idelectro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int updateByExampleSelective(@Param("record") Electroretinografia record, @Param("example") ElectroretinografiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int updateByExample(@Param("record") Electroretinografia record, @Param("example") ElectroretinografiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int updateByPrimaryKeySelective(Electroretinografia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electroretinografia
     *
     * @mbg.generated Tue Oct 01 23:17:02 CDT 2019
     */
    int updateByPrimaryKey(Electroretinografia record);
}