package com.lab.sdt.model;
public class Expediente {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idexpediente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.noExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private String noexpediente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idUsuario
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idusuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idHospital
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idhospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.descripcion
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idEquipo
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idequipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.estatus
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private String estatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idMedico
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idmedico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.nombre
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idEnfermedad
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idenfermedad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.idParametroEXP
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer idparametroexp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente.dosis
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    private Integer dosis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idExpediente
     *
     * @return the value of expediente.idExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdexpediente() {
        return idexpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idExpediente
     *
     * @param idexpediente the value for expediente.idExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdexpediente(Integer idexpediente) {
        this.idexpediente = idexpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.noExpediente
     *
     * @return the value of expediente.noExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public String getNoexpediente() {
        return noexpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.noExpediente
     *
     * @param noexpediente the value for expediente.noExpediente
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setNoexpediente(String noexpediente) {
        this.noexpediente = noexpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idUsuario
     *
     * @return the value of expediente.idUsuario
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdusuario() {
        return idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idUsuario
     *
     * @param idusuario the value for expediente.idUsuario
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idHospital
     *
     * @return the value of expediente.idHospital
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdhospital() {
        return idhospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idHospital
     *
     * @param idhospital the value for expediente.idHospital
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdhospital(Integer idhospital) {
        this.idhospital = idhospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.descripcion
     *
     * @return the value of expediente.descripcion
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.descripcion
     *
     * @param descripcion the value for expediente.descripcion
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idEquipo
     *
     * @return the value of expediente.idEquipo
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdequipo() {
        return idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idEquipo
     *
     * @param idequipo the value for expediente.idEquipo
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.estatus
     *
     * @return the value of expediente.estatus
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.estatus
     *
     * @param estatus the value for expediente.estatus
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idMedico
     *
     * @return the value of expediente.idMedico
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdmedico() {
        return idmedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idMedico
     *
     * @param idmedico the value for expediente.idMedico
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdmedico(Integer idmedico) {
        this.idmedico = idmedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.nombre
     *
     * @return the value of expediente.nombre
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.nombre
     *
     * @param nombre the value for expediente.nombre
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idEnfermedad
     *
     * @return the value of expediente.idEnfermedad
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdenfermedad() {
        return idenfermedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idEnfermedad
     *
     * @param idenfermedad the value for expediente.idEnfermedad
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdenfermedad(Integer idenfermedad) {
        this.idenfermedad = idenfermedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.idParametroEXP
     *
     * @return the value of expediente.idParametroEXP
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getIdparametroexp() {
        return idparametroexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.idParametroEXP
     *
     * @param idparametroexp the value for expediente.idParametroEXP
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setIdparametroexp(Integer idparametroexp) {
        this.idparametroexp = idparametroexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente.dosis
     *
     * @return the value of expediente.dosis
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public Integer getDosis() {
        return dosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente.dosis
     *
     * @param dosis the value for expediente.dosis
     *
     * @mbg.generated Sat Aug 31 14:37:19 CDT 2019
     */
    public void setDosis(Integer dosis) {
        this.dosis = dosis;
    }
}