package com.lab.sdt.model;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.idMaterial
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private Integer idmaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.cantidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private Integer cantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.unidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private String unidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.modelo
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private String modelo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.n_serie
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    private String nSerie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.idMaterial
     *
     * @return the value of material.idMaterial
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public Integer getIdmaterial() {
        return idmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.idMaterial
     *
     * @param idmaterial the value for material.idMaterial
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material
     *
     * @return the value of material.material
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material
     *
     * @param material the value for material.material
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.cantidad
     *
     * @return the value of material.cantidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.cantidad
     *
     * @param cantidad the value for material.cantidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.unidad
     *
     * @return the value of material.unidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public String getUnidad() {
        return unidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.unidad
     *
     * @param unidad the value for material.unidad
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.modelo
     *
     * @return the value of material.modelo
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.modelo
     *
     * @param modelo the value for material.modelo
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.n_serie
     *
     * @return the value of material.n_serie
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public String getnSerie() {
        return nSerie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.n_serie
     *
     * @param nSerie the value for material.n_serie
     *
     * @mbg.generated Sun Aug 04 15:36:28 CDT 2019
     */
    public void setnSerie(String nSerie) {
        this.nSerie = nSerie;
    }
}