package com.lab.sdt.model;

public class Tiponda {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiponda.idTipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    private Integer idtiponda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiponda.tipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    private Integer tiponda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiponda.nombre
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiponda.idTipOnda
     *
     * @return the value of tiponda.idTipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public Integer getIdtiponda() {
        return idtiponda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiponda.idTipOnda
     *
     * @param idtiponda the value for tiponda.idTipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public void setIdtiponda(Integer idtiponda) {
        this.idtiponda = idtiponda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiponda.tipOnda
     *
     * @return the value of tiponda.tipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public Integer getTiponda() {
        return tiponda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiponda.tipOnda
     *
     * @param tiponda the value for tiponda.tipOnda
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public void setTiponda(Integer tiponda) {
        this.tiponda = tiponda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiponda.nombre
     *
     * @return the value of tiponda.nombre
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiponda.nombre
     *
     * @param nombre the value for tiponda.nombre
     *
     * @mbg.generated Thu Jul 25 13:21:07 CDT 2019
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}