package com.lab.sdt.model;

public class Ubicacion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.idEstimulacion
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private Integer idestimulacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.longuitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String longuitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.latitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String latitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.estatus
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String estatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.amplitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String amplitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.frecuencia
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String frecuencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.tiempo
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String tiempo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.onda_P1
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String ondaP1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.onda_P2
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    private String ondaP2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.idEstimulacion
     *
     * @return the value of ubicacion.idEstimulacion
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public Integer getIdestimulacion() {
        return idestimulacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.idEstimulacion
     *
     * @param idestimulacion the value for ubicacion.idEstimulacion
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setIdestimulacion(Integer idestimulacion) {
        this.idestimulacion = idestimulacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.longuitud
     *
     * @return the value of ubicacion.longuitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getLonguitud() {
        return longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.longuitud
     *
     * @param longuitud the value for ubicacion.longuitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setLonguitud(String longuitud) {
        this.longuitud = longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.latitud
     *
     * @return the value of ubicacion.latitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.latitud
     *
     * @param latitud the value for ubicacion.latitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.estatus
     *
     * @return the value of ubicacion.estatus
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.estatus
     *
     * @param estatus the value for ubicacion.estatus
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.amplitud
     *
     * @return the value of ubicacion.amplitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getAmplitud() {
        return amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.amplitud
     *
     * @param amplitud the value for ubicacion.amplitud
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setAmplitud(String amplitud) {
        this.amplitud = amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.frecuencia
     *
     * @return the value of ubicacion.frecuencia
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getFrecuencia() {
        return frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.frecuencia
     *
     * @param frecuencia the value for ubicacion.frecuencia
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setFrecuencia(String frecuencia) {
        this.frecuencia = frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.tiempo
     *
     * @return the value of ubicacion.tiempo
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getTiempo() {
        return tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.tiempo
     *
     * @param tiempo the value for ubicacion.tiempo
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.onda_P1
     *
     * @return the value of ubicacion.onda_P1
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getOndaP1() {
        return ondaP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.onda_P1
     *
     * @param ondaP1 the value for ubicacion.onda_P1
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setOndaP1(String ondaP1) {
        this.ondaP1 = ondaP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.onda_P2
     *
     * @return the value of ubicacion.onda_P2
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public String getOndaP2() {
        return ondaP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.onda_P2
     *
     * @param ondaP2 the value for ubicacion.onda_P2
     *
     * @mbg.generated Tue Aug 27 21:08:00 CDT 2019
     */
    public void setOndaP2(String ondaP2) {
        this.ondaP2 = ondaP2;
    }
}