package com.lab.sdt.model;

import java.util.Date;

public class ExpedienteConsulta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.idExpeConsul
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idexpeconsul;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.fechaConsulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Date fechaconsulta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.idExpediente
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idexpediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.descripcion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.peso
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String peso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.p_mayor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String pMayor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.p_menor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String pMenor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.temperatura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String temperatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.altura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String altura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.masa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String masaCorp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column expediente_consulta.grasa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String grasaCorp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.idExpeConsul
	 * @return  the value of expediente_consulta.idExpeConsul
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdexpeconsul() {
		return idexpeconsul;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.idExpeConsul
	 * @param idexpeconsul  the value for expediente_consulta.idExpeConsul
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdexpeconsul(Integer idexpeconsul) {
		this.idexpeconsul = idexpeconsul;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.fechaConsulta
	 * @return  the value of expediente_consulta.fechaConsulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Date getFechaconsulta() {
		return fechaconsulta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.fechaConsulta
	 * @param fechaconsulta  the value for expediente_consulta.fechaConsulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setFechaconsulta(Date fechaconsulta) {
		this.fechaconsulta = fechaconsulta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.idExpediente
	 * @return  the value of expediente_consulta.idExpediente
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdexpediente() {
		return idexpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.idExpediente
	 * @param idexpediente  the value for expediente_consulta.idExpediente
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdexpediente(Integer idexpediente) {
		this.idexpediente = idexpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.descripcion
	 * @return  the value of expediente_consulta.descripcion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.descripcion
	 * @param descripcion  the value for expediente_consulta.descripcion
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.peso
	 * @return  the value of expediente_consulta.peso
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getPeso() {
		return peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.peso
	 * @param peso  the value for expediente_consulta.peso
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setPeso(String peso) {
		this.peso = peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.p_mayor
	 * @return  the value of expediente_consulta.p_mayor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getpMayor() {
		return pMayor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.p_mayor
	 * @param pMayor  the value for expediente_consulta.p_mayor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setpMayor(String pMayor) {
		this.pMayor = pMayor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.p_menor
	 * @return  the value of expediente_consulta.p_menor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getpMenor() {
		return pMenor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.p_menor
	 * @param pMenor  the value for expediente_consulta.p_menor
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setpMenor(String pMenor) {
		this.pMenor = pMenor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.temperatura
	 * @return  the value of expediente_consulta.temperatura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getTemperatura() {
		return temperatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.temperatura
	 * @param temperatura  the value for expediente_consulta.temperatura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setTemperatura(String temperatura) {
		this.temperatura = temperatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.altura
	 * @return  the value of expediente_consulta.altura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getAltura() {
		return altura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.altura
	 * @param altura  the value for expediente_consulta.altura
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setAltura(String altura) {
		this.altura = altura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.masa_corp
	 * @return  the value of expediente_consulta.masa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getMasaCorp() {
		return masaCorp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.masa_corp
	 * @param masaCorp  the value for expediente_consulta.masa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setMasaCorp(String masaCorp) {
		this.masaCorp = masaCorp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column expediente_consulta.grasa_corp
	 * @return  the value of expediente_consulta.grasa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getGrasaCorp() {
		return grasaCorp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column expediente_consulta.grasa_corp
	 * @param grasaCorp  the value for expediente_consulta.grasa_corp
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setGrasaCorp(String grasaCorp) {
		this.grasaCorp = grasaCorp;
	}
}