package com.lab.sdt.model;

import java.util.Date;

public class Mantenimiento {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.idMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private Integer idmantenimiento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.fechaMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private Date fechamantenimiento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.falla
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private String falla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.tipoActualizacion
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private String tipoactualizacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.idUsuario
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private Integer idusuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.estatus
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private String estatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.longuitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private String longuitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento.latitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    private String latitud;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.idMantenimiento
     *
     * @return the value of mantenimiento.idMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public Integer getIdmantenimiento() {
        return idmantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.idMantenimiento
     *
     * @param idmantenimiento the value for mantenimiento.idMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setIdmantenimiento(Integer idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.fechaMantenimiento
     *
     * @return the value of mantenimiento.fechaMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public Date getFechamantenimiento() {
        return fechamantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.fechaMantenimiento
     *
     * @param fechamantenimiento the value for mantenimiento.fechaMantenimiento
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setFechamantenimiento(Date fechamantenimiento) {
        this.fechamantenimiento = fechamantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.falla
     *
     * @return the value of mantenimiento.falla
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public String getFalla() {
        return falla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.falla
     *
     * @param falla the value for mantenimiento.falla
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setFalla(String falla) {
        this.falla = falla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.tipoActualizacion
     *
     * @return the value of mantenimiento.tipoActualizacion
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public String getTipoactualizacion() {
        return tipoactualizacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.tipoActualizacion
     *
     * @param tipoactualizacion the value for mantenimiento.tipoActualizacion
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setTipoactualizacion(String tipoactualizacion) {
        this.tipoactualizacion = tipoactualizacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.idUsuario
     *
     * @return the value of mantenimiento.idUsuario
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public Integer getIdusuario() {
        return idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.idUsuario
     *
     * @param idusuario the value for mantenimiento.idUsuario
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.estatus
     *
     * @return the value of mantenimiento.estatus
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.estatus
     *
     * @param estatus the value for mantenimiento.estatus
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.longuitud
     *
     * @return the value of mantenimiento.longuitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public String getLonguitud() {
        return longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.longuitud
     *
     * @param longuitud the value for mantenimiento.longuitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setLonguitud(String longuitud) {
        this.longuitud = longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento.latitud
     *
     * @return the value of mantenimiento.latitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento.latitud
     *
     * @param latitud the value for mantenimiento.latitud
     *
     * @mbg.generated Sat Aug 24 17:39:43 CDT 2019
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
}