package com.lab.sdt.model;

public class NumOnda {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column num_onda.idNum_Onda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idnumOnda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column num_onda.idOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idonda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column num_onda.idTipOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idtiponda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column num_onda.nombre
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column num_onda.idNum_Onda
	 * @return  the value of num_onda.idNum_Onda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdnumOnda() {
		return idnumOnda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column num_onda.idNum_Onda
	 * @param idnumOnda  the value for num_onda.idNum_Onda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdnumOnda(Integer idnumOnda) {
		this.idnumOnda = idnumOnda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column num_onda.idOnda
	 * @return  the value of num_onda.idOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdonda() {
		return idonda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column num_onda.idOnda
	 * @param idonda  the value for num_onda.idOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdonda(Integer idonda) {
		this.idonda = idonda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column num_onda.idTipOnda
	 * @return  the value of num_onda.idTipOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdtiponda() {
		return idtiponda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column num_onda.idTipOnda
	 * @param idtiponda  the value for num_onda.idTipOnda
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdtiponda(Integer idtiponda) {
		this.idtiponda = idtiponda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column num_onda.nombre
	 * @return  the value of num_onda.nombre
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column num_onda.nombre
	 * @param nombre  the value for num_onda.nombre
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}