package com.lab.sdt.model;

import java.util.Date;

public class Presionintraocular {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column presionintraocular.id
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column presionintraocular.idExp_Consulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Integer idexpConsulta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column presionintraocular.p_Izq
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String pIzq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column presionintraocular.p_Der
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private String pDer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column presionintraocular.fecha
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	private Date fecha;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column presionintraocular.id
	 * @return  the value of presionintraocular.id
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column presionintraocular.id
	 * @param id  the value for presionintraocular.id
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column presionintraocular.idExp_Consulta
	 * @return  the value of presionintraocular.idExp_Consulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Integer getIdexpConsulta() {
		return idexpConsulta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column presionintraocular.idExp_Consulta
	 * @param idexpConsulta  the value for presionintraocular.idExp_Consulta
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setIdexpConsulta(Integer idexpConsulta) {
		this.idexpConsulta = idexpConsulta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column presionintraocular.p_Izq
	 * @return  the value of presionintraocular.p_Izq
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getpIzq() {
		return pIzq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column presionintraocular.p_Izq
	 * @param pIzq  the value for presionintraocular.p_Izq
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setpIzq(String pIzq) {
		this.pIzq = pIzq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column presionintraocular.p_Der
	 * @return  the value of presionintraocular.p_Der
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public String getpDer() {
		return pDer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column presionintraocular.p_Der
	 * @param pDer  the value for presionintraocular.p_Der
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setpDer(String pDer) {
		this.pDer = pDer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column presionintraocular.fecha
	 * @return  the value of presionintraocular.fecha
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column presionintraocular.fecha
	 * @param fecha  the value for presionintraocular.fecha
	 * @mbg.generated  Tue Nov 26 16:14:00 CST 2019
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
}